function G5R1PreTreinotobispectrum = importfile_bispectrum(filename, dataLines)
%IMPORTFILE Import data from a text file
%  G5R1PRETREINOTOBISPECTRUM = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  G5R1PRETREINOTOBISPECTRUM = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  G5R1PreTreinotobispectrum = importfile("/home/matheus/Documents/repositories/bispectrum_real_data_analysis/bispectrum_real_data_analysis/scripts/rats_analysis/group5rat1/G5-R1_PreTreino_to_bispectrum.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 06-Apr-2023 17:32:08

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time", "CS_modulating", "Inferior_colliculus", "event"];
opts.VariableTypes = ["double", "double", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "event", "EmptyFieldRule", "auto");

% Import the data
G5R1PreTreinotobispectrum = readtable(filename, opts);

end