
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 20-Aug-2022 02:13:37

% Import the file
relative_path = "../data/F04__T_data.mat/";
abs_path = GetFullPath(fullfile(cd, relative_path));
newData1 = load('-mat', abs_path);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end


