import pandas as pd
import plotly.express as px
import os
from plotly.subplots import make_subplots
from bispectrum_real_data_analysis.scripts.utils import standardize_array
from loguru import logger

"""
This function plots the data from the csv file generated by the script generate_bispectrum_of_data.py.
To filter one channel, double click one of the lines in the legend. then, select the other corresponding line (if you
clicked in the amplitude, select the phase line and vice versa). All the 16 channels are plotted in the same figure.
The plot in the first row is the amplitude and the plot in the second row is the phase.
"""

if __name__ == "__main__":

    # Select which data to plot
    BASE_PATH = os.getcwd() + "/bispectrum_real_data_analysis/data"

    prefix_rat = "bispectrum_rato-001"

    files_to_plot = [f"{BASE_PATH}/{f}" for f in os.listdir(BASE_PATH) if os.path.isfile(os.path.join(BASE_PATH, f)) and f.startswith(prefix_rat)]   

    standardize = True

    for file in files_to_plot:
        logger.info(f"Plotting {file.split('/')[-1]}")
        df = pd.read_csv(file, delimiter=',', encoding="utf8")

        amplitudes = df.iloc[:, 1:17]

        if standardize:
            amplitudes = amplitudes.apply(standardize_array)

        phases = df.iloc[:, 17:33]
        title = file.split('/')[-1].split('.')[0]
        
        fig = make_subplots(rows=2, cols=1)

        fig.update_layout(
            font_family="Courier New",
            font_color="blue",
            title_font_family="Times New Roman",
            title_font_color="black",
            legend_title_font_color="green",
            title=title
        )

        amplitudes = px.line(amplitudes, x=df.iloc[:, 0], y=amplitudes.columns)
        phases = px.line(phases, x=df.iloc[:, 0], y=phases.columns)
        
        for amplitude in amplitudes['data']:
            fig.add_trace(amplitude, row=1, col=1)
        for phase in phases['data']:
            fig.add_trace(phase, row=2, col=1)
        fig.show()
    logger.success("Done!")
