%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /home/matheus/Documents/repositories/bispectrum_real_data_analysis/bispectrum_real_data_analysis/data/rats/G5-R1_Salina_to_bispectrum.csv
%
% Auto-generated by MATLAB on 29-May-2023 22:34:14

%% Set up the Import Options and import the data

close all;
clear;
clc;

opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Time1", "CS_modulating1", "Inferior_colliculus1", "event1"];
opts.VariableTypes = ["double", "double", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "event1", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("/home/matheus/Documents/repositories/bispectrum_real_data_analysis/bispectrum_real_data_analysis/data/rats/G5-R1_Salina_to_bispectrum.csv", opts);

%% Convert to output type
Time1 = tbl.Time1;
CS_modulating1 = tbl.CS_modulating1;
Inferior_colliculus1 = tbl.Inferior_colliculus1;
events = tbl.event1;

%% Clear temporary variables
clear opts tbl
%%
ic1 = Inferior_colliculus1(events == "event_1");
ic1 = ic1(5000:end);
cs1 = CS_modulating1(events == "event_1");
cs1 = cs1(5000:end);



